name: restaurante_tpv
description: TPV para restaurante - Sunmi V2
publish_to: 'none'
version: 1.0.2

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  shared_preferences: ^2.5.5
  provider: ^6.1.5+1
  flutter_secure_storage: ^10.0.0
  sunmi_printer_plus: ^4.1.1
  intl: ^0.20.2
  connectivity_plus: ^7.1.1
  package_info_plus: ^8.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
